name: Build and publish project

on:
  push:
    branches: ["main"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
      - name: Build
        run: ./gradlew build
      - name: Publish
        run: ./gradlew publish
        env:
          REPO_USERNAME: ${{ vars.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}